name: Deploy to VPS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo chown -R ubuntu:ubuntu /var/www/kino_bot
            cd /var/www/kino_bot
            git pull origin main
            sudo chown -R www-data:www-data /var/www/kino_bot
            sudo chown ubuntu:ubuntu /var/www/kino_bot/.git -R
            sudo chmod -R 755 /var/www/kino_bot
            sudo chmod 777 /var/www/kino_bot/logs
